### ISSUE TITLE
Wrong reference to string instead of byte stream

### ISSUE THREAD

**Issue by planck2007** [mousset/qubic#6]
In `instrument.py` at lines 385 and 397 there is a reference to the labels of the `names` dictionary.
`line 385: indf = names.index('ndf') - 2`
`line 392: ib2b = names.index('ba2ba')`
This raises an error because the labels have been defined as byte streams (i.e. `b'ndf'` and `b'ba2ba`)
Therefore the above lines should change to:
`line 385: indf = names.index(b'ndf') - 2`
`line 392: ib2b = names.index(b'ba2ba')`

**Comment by mousset** [comment]
Thanks for this remark ! I just made the modification that you suggested.
