### ISSUE TITLE
Deprecated use of non-tuple sequence for multidimensional indexing

### ISSUE THREAD

**Issue by planck2007** [mousset/qubic#8]
In lines 3353 and 3363 of core.py there is a deprecated use on non-tuple sequences for multidimensional indexing. Here follows the warning: 

`core.py:3353: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  i = input[sins[0]]`

`core.py:3363: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  i = input[sin]`

**Comment by mousset** [comment]
Yes, I know this warning. Before there was the same warning for a script in the qubic soft and I corrected it as they say and it solved the issue.
core.py is part of pyoperators so this is why I didn't solve it. I think Steve could do the modification on his fork.

**Comment by satorchi** [comment]
I have fixed the error in pyoperators.  Please tell me if it's okay, or if I have introduced a new bug.
